### ISSUE TITLE
ERROR: OmniGibson import failed, please make sure you have omnigibson installed before downloading datasets

### ISSUE THREAD

**Issue by disunlike** [StanfordVL/BEHAVIOR-1K#1904]
```shell
# Clone the latest stable release (recommended)
git clone -b v3.7.1 https://github.com/StanfordVL/BEHAVIOR-1K.git
cd BEHAVIOR-1K

# Run the setup script
./setup.sh --new-env --omnigibson --bddl --joylo --dataset
```

on Ubuntu22.04. A error happen when I run command "./setup.sh --new-env --omnigibson --bddl --joylo --dataset"
--------
home/youlika/miniconda3/envs/behavior/lib/python3.10/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:109.)
  return torch._C._cuda_getDeviceCount() > 0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/youlika/code/github/BEHAVIOR-1K/OmniGibson/omnigibson/__init__.py", line 9, in <module>
    from omnigibson.envs import Environment, VectorEnvironment
  File "/home/youlika/code/github/BEHAVIOR-1K/OmniGibson/omnigibson/envs/__init__.py", line 1, in <module>
    from omnigibson.envs.data_wrapper import DataCollectionWrapper, DataPlaybackWrapper
  File "/home/youlika/code/github/BEHAVIOR-1K/OmniGibson/omnigibson/envs/data_wrapper.py", line 22, in <module>
    from omnigibson.tasks.behavior_task import BehaviorTask
  File "/home/youlika/code/github/BEHAVIOR-1K/OmniGibson/omnigibson/tasks/__init__.py", line 1, in <module>
    from omnigibson.tasks.behavior_task import BehaviorTask
  File "/home/youlika/code/github/BEHAVIOR-1K/OmniGibson/omnigibson/tasks/behavior_task.py", line 24, in <module>
    from omnigibson.scenes.scene_base import Scene
  File "/home/youlika/code/github/BEHAVIOR-1K/OmniGibson/omnigibson/scenes/__init__.py", line 1, in <module>
    from omnigibson.scenes.interactive_traversable_scene import InteractiveTraversableScene
  File "/home/youlika/code/github/BEHAVIOR-1K/OmniGibson/omnigibson/scenes/interactive_traversable_scene.py", line 5, in <module>
    from omnigibson.scenes.traversable_scene import TraversableScene
  File "/home/youlika/code/github/BEHAVIOR-1K/OmniGibson/omnigibson/scenes/traversable_scene.py", line 2, in <module>
    from omnigibson.scenes.scene_base import Scene
  File "/home/youlika/code/github/BEHAVIOR-1K/OmniGibson/omnigibson/scenes/scene_base.py", line 29, in <module>
    from omnigibson.transition_rules import TransitionRuleAPI
  File "/home/youlika/code/github/BEHAVIOR-1K/OmniGibson/omnigibson/transition_rules.py", line 36, in <module>
    from omnigibson.utils.bddl_utils import translate_bddl_recipe_to_og_recipe, translate_bddl_washer_rule_to_og_washer_rule
  File "/home/youlika/code/github/BEHAVIOR-1K/OmniGibson/omnigibson/utils/bddl_utils.py", line 267, in <module>
    BEHAVIOR_ACTIVITIES = sorted(os.listdir(os.path.join(os.path.dirname(bddl.__file__), "activity_definitions")))
  File "/home/youlika/miniconda3/envs/behavior/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
ERROR: OmniGibson import failed, please make sure you have omnigibson installed before downloading datasets

**Comment by wensi-ai** [comment]
This issue should now be fixed, please try installing with the latest main branch.

**Comment by benjaminalt** [comment]
This issue persists on the current main branch, Ubuntu 24.04. and a fresh conda environment:

  File "/home/balt/devel/BEHAVIOR-1K/OmniGibson/omnigibson/utils/bddl_utils.py", line 267, in <module>
    BEHAVIOR_ACTIVITIES = sorted(os.listdir(os.path.join(os.path.dirname(bddl.__file__), "activity_definitions")))
  File "/home/balt/Tools/miniforge3/envs/behavior/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
ERROR: OmniGibson import failed, please make sure you have omnigibson installed before downloading datasets

EDIT: The workaround from https://github.com/StanfordVL/BEHAVIOR-1K/issues/1900 still works.
